_format_version: "3.0"
_transform: true

# Consumers: qui peut accéder aux services
consumers:
  - username: fleet-client

# Secrets JWT pour authentification
jwt_secrets:
  - consumer: fleet-client
    key: fleet-key
    secret: fleet-secret-123
    algorithm: HS256

# Services exposés par Kong
services:
  - name: quarkus-service
    url: http://quarkus:8080
    routes:
      - name: quarkus-products
        paths:
          - /api/products
      - name: quarkus-orders
        paths:
          - /api/orders
    plugins:
      # JWT obligatoire pour accéder au service
      - name: jwt
      # Limitation du nombre de requêtes pour éviter les abus
      - name: rate-limiting
        config:
          minute: 100
          policy: local
      # Logging des requêtes pour audit et sécurité
      - name: file-log
        config:
          path: /usr/local/kong/logs/kong_requests.log
          custom_fields_by_lua:
            consumer_username: "$consumer.username"
            request_path: "$request.path"
            request_method: "$request.method"
            response_status: "$response.status"

# Plugins globaux (ex: monitoring)
plugins:
  - name: prometheus
    enabled: true
